### ISSUE TITLE
ERROR [io.qua.sch.run.SimpleScheduler]

### ISSUE THREAD

**Issue by ithakaa** [Ogefest/filehunter#1]
Hi

I'm getting the below error when performing a search after the setup.

2021-09-22 23:18:07,001 ERROR [io.qua.sch.run.SimpleScheduler] (executor-thread-1) Error occured while executing task for trigger IntervalTrigger [id=1_com.ogefest.filehunter.App_ScheduledInvoker_tasks_9fa5226e0823d752ee38aee4995778e4cf0944ec, interval=3000]: java.lang.NullPointerException
        at com.ogefest.filehunter.IndexWrite.addDocument(IndexWrite.java:57)
        at com.ogefest.filehunter.task.IndexStructure.proceedPath(IndexStructure.java:123)
        at com.ogefest.filehunter.task.IndexStructure$1.preVisitDirectory(IndexStructure.java:69)
        at com.ogefest.filehunter.task.IndexStructure$1.preVisitDirectory(IndexStructure.java:65)
        at java.nio.file.Files.walkFileTree(Files.java:2732)
        at java.nio.file.Files.walkFileTree(Files.java:2797)
        at com.ogefest.filehunter.task.IndexStructure.indexPath(IndexStructure.java:65)
        at com.ogefest.filehunter.task.IndexStructure.run(IndexStructure.java:45)
        at com.ogefest.filehunter.App.tasks(App.java:61)
        at com.ogefest.filehunter.App_ScheduledInvoker_tasks_9fa5226e0823d752ee38aee4995778e4cf0944ec.invokeBean(App_ScheduledInvoker_tasks_9fa5226e0823d752ee38aee4995778e4cf0944ec.zig:46)
        at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.run(SimpleScheduler.java:259)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:541)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

**Comment by Ogefest** [comment]
Hello my first issue reporter. I can confirm that this exception could occur in some cases. I'll try today or tomorrow fix this issue and release next version.

**Comment by ithakaa** [comment]
Thanks, that would be great.
Question, can filehunter index my files and contents?

**Comment by ithakaa** [comment]
> Hello my first issue reporter. I can confirm that this exception could occur in some cases. I'll try today or tomorrow fix this issue and release next version.

Thank you !!

Looking forward to indexing my files

**Comment by Ogefest** [comment]
Good news today, new release ready to download. Mostly focused on integration apache tika to read contents of documents and make it searchable but your bug is also fixed. As always any feedback about the app is welcome. Enjoy.
